apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "productpage.fullname" . }}-canary
  labels:
    app: {{ template "productpage.name" . }}-canary
    chart: {{ template "productpage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "productpage.name" . }}-canary
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "productpage.name" . }}-canary
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-canary
          image: "{{ .Values.image-canary.repository }}:{{ .Values.image-canary.tag }}"
          imagePullPolicy: {{ .Values.image-canary.pullPolicy }}
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
